# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_password',
            new_name='salt',
        ),
    ]
